$t("アンソン·オープンソース·コミュニティ");
$r("menu-home", "ホーム");
$r("menu-dl", "ダウンロード");
$r("menu-fb", "フィードバック");
$r("menu-repo", "リポジトリ");
$r("menu-l10n", "ローカライゼーション");
$r("row-dl", "ダウンロード");
$r("row-dl-text", "AOSCの最新作をダウンロードしましょう！");
$r("row-dl-btn", "行く&raquo;");
$e();